FROM node:14

RUN mkdir -p /usr/src/node-api
WORKDIR /usr/src/node-api
COPY . .

ENV NODE_ENV=production
ENV NODE_APP_CORS_URL=https://questionnaire-fe.azurewebsites.net
ENV PG_CONNSTR=postgres://agjjremw:vwSHOh00HFUE3X0Oi03BQUZQT1x7dRxt@satao.db.elephantsql.com:5432/agjjremw

RUN npm install --production && npm run build:prod

EXPOSE 3000

CMD [ "npm", "start" ]
